# Generated by Django 6.0.6 on 2026-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('projects', '0002_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='projects', to='labels.label'),
        ),
    ]
