# Generated by Django 6.0.6 on 2026-06-29 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
