# Generated by Django 6.0.6 on 2026-06-30 08:45

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_column_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['column', 'position']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('TESTING', 'Testing'), ('DONE', 'Done'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Logged hours', max_digits=6),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TASK', 'Task'), ('BUG', 'Bug'), ('STORY', 'Story'), ('EPIC', 'Epic'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement'), ('SPIKE', 'Spike')], default='TASK', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watching_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
