# Generated by Django 6.0.6 on 2026-07-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('tasks', '0005_alter_task_options_remove_task_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='milestones.milestone'),
        ),
    ]
