# Generated by Django 6.0.6 on 2026-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
