# Generated by Django 6.0.6 on 2026-07-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_alter_milestone_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='milestone',
            name='unique_project_milestone_name',
        ),
    ]
