# Generated by Django 6.0.6 on 2026-07-15 07:00

import common.permissions.mixins
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('color', models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid 6-digit hex color')])),
                ('description', models.TextField(blank=True)),
                ('position', models.DecimalField(decimal_places=20, default=0.0, max_digits=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_scoped_labels', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('workspace_id', 'project', 'name')},
            },
            bases=(common.permissions.mixins.WorkspaceResourceMixin, models.Model),
        ),
    ]
