# Generated by Django 6.0.6 on 2026-07-15 11:20

import common.permissions.mixins
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0008_task_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DecimalField(decimal_places=2, help_text='Duration spent in hours. Must be positive.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of work performed.')),
                ('logged_at', models.DateField(default=django.utils.timezone.now, help_text='The date the work was actually performed.')),
                ('is_locked', models.BooleanField(default=False, help_text='Once locked (billing finalized), the log cannot be edited or deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at', '-created_at'],
            },
            bases=(common.permissions.mixins.WorkspaceResourceMixin, models.Model),
        ),
    ]
